# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botform', '0002_auto_20171123_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='generate_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forms',
            name='pdf_output_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
