# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botform', '0003_auto_20171123_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='pdf',
            field=models.URLField(blank=True, help_text='PDF Output URL', max_length=400, null=True),
        ),
    ]
