# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botform', '0004_submissions_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='reference',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
